give_money_every_second: 600
afk_payout: false
info: You can add more payouts by copy and paste. Dont forget to change the number!
store-money-in-bank: false
payouts:
  1:
    payout_amount: 50
    max_payout_per_day: 1000
    permission:
  2:
    payout_amount: 100
    max_payout_per_day: 10000
    commands:
      - /give %player% diamond 1
    permission: tim.vip
message: "&aYou have got &c%money% &afor 10 minutes online time!"
message_payoutlimit_reached: "§cYou have reached the payoutlimit today. You got 0$"
message_afk: "&cYou havn't got money because you were afk!"
display-messages-in-chat: true
display-messages-in-actionbar: true
display-messages-in-actionbar-time: 10
message_atm_noperms: "§cYou dont have permissions to use ATM's!"
message_atm_nomoneyinbank: "§cYou don't have enought money in bank!"
message_atm_nomoney: "§cYou don't have enought money!"
atm_title: "§cATM"
atm_withdraw: "§cWithdraw"
atm_deposit: "§cDeposit"
atm_balance: "§cBank balance:"
configuration-version: 8